openapi: 3.0.3
info:
  title: "SmartOffice"
  description: Book your workspace smartly!
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: booking
    description: Бронирование рабочего места
paths:
  /booking/create:
    post:
      tags:
        - booking
      summary: Create booking
      operationId: bookingCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingCreateResponse'                
  /booking/read:
    post:
      tags:
        - booking
      summary: Read booking by id
      operationId: bookingRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingReadResponse'

  /ad/update:
    post:
      tags:
        - ad
      summary: Update ad
      operationId: adUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdUpdateResponse'
  /ad/delete:
    post:
      tags:
        - ad
      summary: Delete ad
      operationId: adDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDeleteResponse'
  /ad/search:
    post:
      tags:
        - ad
      summary: Search ad
      operationId: adSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdSearchResponse'


components:
  schemas:

    # GENERAL ======================

    UserId:
      type: string
      description: Идентификатор пользователя

    BookingId:
      type: string
      description: Идентификатор бронирования

    AdLock:
      type: string
      description: Версия оптимистичной блокировки  

    DealSide:
      type: string
      description: 'Сторона сделки: спрос или предложение'
      enum:
        - demand
        - supply

    AdVisibility:
      type: string
      description: 'Тип видимости объявления. Возможные значения: видит только владелец, только зарегистрированный в системе пользователь, видимо всем'
      enum:
        - ownerOnly
        - registeredOnly
        - public      

    BaseAd:
      type: object
      description: Объект описывает свойства, одинаковые для create и update
      properties:
        title:
          type: string
          description: Заголовок объявления
        description:
          type: string
          description: Описание объявления
        adType:
          $ref: '#/components/schemas/DealSide'
        visibility:
          $ref: '#/components/schemas/AdVisibility'      

    # REQUESTS SCHEMAS ======================

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дискриминатор для вычисления типа запроса
          example: create
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/BookingCreateRequest'
          read:   '#/components/schemas/BookingReadRequest'
          update: '#/components/schemas/AdUpdateRequest'
          delete: '#/components/schemas/AdDeleteRequest'
          search: '#/components/schemas/AdSearchRequest'

    # 1. create

    BookingCreateObject:
      allOf:
        - $ref: '#/components/schemas/BaseAd'

    BookingCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BookingRequestDebug'
        - type: object
          properties:
            booking:
              $ref: '#/components/schemas/BookingCreateObject'

    # 2. read

    BookingReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/BookingId'

    BookingReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BookingRequestDebug'
        - type: object
          properties:
            booking:
              $ref: '#/components/schemas/BookingReadObject'

    


    # RESPONSE SCHEMAS ======================

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дискриминатор для вычисления типа запроса
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/BookingCreateResponse'
          read:   '#/components/schemas/BookingReadResponse'
          update: '#/components/schemas/AdUpdateResponse'
          delete: '#/components/schemas/AdDeleteResponse'
          search: '#/components/schemas/AdSearchResponse'
          init: '#/components/schemas/AdInitResponse'





    AdInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'





    AdUpdateObject:
      allOf:
        - $ref: '#/components/schemas/BaseAd'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/BookingId'
            lock:
              $ref: '#/components/schemas/AdLock'

    AdUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BookingRequestDebug'
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/AdUpdateObject'

    AdDeleteObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/BookingId'
            lock:
              $ref: '#/components/schemas/AdLock'

    AdDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BookingRequestDebug'
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/AdDeleteObject'

    AdSearchFilter:
      type: object
      description: Набор фильтров для поиска
      properties:
        searchString:
          type: string
          description: Поисковая строка, которая будет искаться в объявлениях
        ownerId:
          $ref: '#/components/schemas/UserId'
        adType:
          $ref: '#/components/schemas/DealSide'

    AdSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/BookingRequestDebug'
        - type: object
          properties:
            adFilter:
              $ref: '#/components/schemas/AdSearchFilter'


    AdResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseAd'
        - type: object
          description: Объект, который возвращается в ответе бэкенда
          properties:
            id:
              $ref: '#/components/schemas/BookingId'
            ownerId:
              $ref: '#/components/schemas/UserId'
            lock:
              $ref: '#/components/schemas/AdLock'
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/AdPermissions'

    AdPermissions:
      type: string
      description: Доступы для клиента для операций над объявлением
      enum:
        - read
        - update
        - delete
        - makeVisiblePublic
        - makeVisibleOwn
        - makeVisibleGroup

    AdResponseSingle:
      allOf:
        - type: object
          description: Ответ с одним объектом объявления
          properties:
            ad:
              $ref: '#/components/schemas/AdResponseObject'

    AdResponseMulti:
      allOf:
        - type: object
          description: Список найденных объектов
          properties:
            ads:
              type: array
              items:
                $ref: '#/components/schemas/AdResponseObject'

    BookingCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    BookingReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseSingle'

    AdSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/AdResponseMulti'


    # STUBS ======================
    BookingRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    BookingRequestDebugStubs:
      type: string
      description: Перечисления всех стабов
      enum:
        - success
        - notFound
        - badId
        - badTitle
        - badDescription
        - badVisibility
        - cannotDelete
        - badSearchString        

    BookingDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/BookingRequestDebugMode'
        stub:
          $ref: '#/components/schemas/BookingRequestDebugStubs'        

    BookingRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/BookingDebug'



